<a href="https://colab.research.google.com/github/jiinpark21/ESAA_24-1/blob/main/1%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C_0308_%EC%84%B8%EC%85%98_%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np. __version__)
print(np.show_config())

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
b = np.array([1,2])
print(b.nbytes)
print(b.size*b.itemsize)

16
16


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
a = np.arange(50)
reverse_a = np.sort(a)[::-1]
print(reverse_a)

# a = a[::-1] 도 가능

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a = np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
a = np.random.rand(3,3,3)
print(a)

# a = np.random.random((3,3,3))

[[[0.51021361 0.67438249 0.83538105]
  [0.64482306 0.98769712 0.42551095]
  [0.39458759 0.84778878 0.0189731 ]]

 [[0.80951871 0.36559021 0.55924768]
  [0.31349662 0.22852762 0.05904235]
  [0.30179267 0.18357242 0.38819043]]

 [[0.51377702 0.21894297 0.60201639]
  [0.09295153 0.08309485 0.01481947]
  [0.2458607  0.77919837 0.53641974]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
a = np.random.rand(10,10)
print('minimum:',np.min(a),' maximum:', np.max(a))

minimum: 0.00023423420766344183  maximum: 0.992752286665842


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
a = np.random.rand(30)
print(np.mean(a))

0.4926826524035491


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones((3,3),dtype='int64')
a[1,1]=0
print(a)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [ ]:
# 3x3 이상의 2d array

b = np.ones((5,5))
b[1:-1,1:-1] = 0
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
a = np.diag([1,2,3,4], k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
a = np.zeros((8,8), dtype=int)
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
import random

a = np.random.random((5,5))
a_mean = np.mean(a)
a_std = np.std(a)
a_norm = (a-a_mean)/a_std
print(a_norm)
# print(np.mean(a_norm), np.std(a_norm))

[[ 0.45571813  0.33785897 -0.77785012  0.8541663  -1.44323722]
 [ 0.36556857  1.5196587  -0.19372212  1.48226539 -1.40362365]
 [-1.02147835  1.48343833  0.02716821 -0.59086174  0.89635201]
 [ 0.5629387   1.40323809 -1.50454457  0.9677211  -1.17188975]
 [-0.82919178  0.36200312 -0.93955011  0.38517458 -1.22732076]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
dot_product = np.dot(a,b)
print(dot_product)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = np.arange(10)
a[3:9] *= -1
print(a)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) # 결과: 9
from numpy import *
print(sum(range(5),-1)) # 결과: 10

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.array([1,2,3])
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# Z<Z>Z 는 illegal

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# 0끼리 나누기 불가
print(np.array(0) / np.array(0)) # 결과: nan

# array 나눗셈에서 몫 구하기 가능
print(np.array(0) // np.array(0)) # 결과: 0

# nan 값을 정수로 cast 할 수 없다
print(np.array([np.nan]).astype(int).astype(float)) # 결과:

nan
0
[-9.22337204e+18]


<ipython-input-28-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-28-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-28-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


<br><br><br>
#**0308 과제 (26~39)**

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [1]:
import numpy as np

In [81]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(Z1,Z2)
print(np.intersect1d(Z1,Z2))

[1 3 8 4 2 0 5 1 3 6] [4 7 8 7 3 5 0 8 6 0]
[0 3 4 5 6 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) # 결과: False

False


<ipython-input-3-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [82]:
july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [11]:
A = np.ones(3)*2
B = np.ones(3)*4
np.add(A,B,out=B) # A+B 계산 후 B에 결과 저장
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-6., -6., -6.])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [18]:
# First method
A = np.random.uniform(0,10,10)
integer_A = A-A%1
print(integer_A)

# Second method
B = np.random.uniform(0,10,10)
integer_B = B // 1
print(integer_B)

[8. 5. 5. 8. 1. 6. 0. 6. 5. 5.]
[8. 6. 6. 6. 6. 7. 1. 1. 1. 8.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [19]:
A = np.zeros((5,5))
A += np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [40]:
A = np.random.random(10)
print(np.sort(A))

[0.05743675 0.20339944 0.41256056 0.43578433 0.54394769 0.57364186
 0.58543749 0.79285325 0.86999586 0.98609346]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [46]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
np.array_equal(A,B)

[1 1 0 0 1] [1 0 0 1 1]


False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [23]:
A = np.random.random((10,2))
x = A[:,0] #0열
y = A[:,1] #1열
r = np.sqrt(x**2+y**2) # distance from origin to (x,y)
p = np.arctan2(y,x) # 극좌표계(angle from the x-axis)
print(r)
print(p)

[0.37942204 1.15831048 0.66306369 0.31815351 0.49606996 0.8293071
 1.01719983 0.58810957 0.64421781 0.88980694]
[0.72668352 0.59825479 1.16398746 0.43841769 1.49225441 0.89216699
 0.6673336  1.41288929 0.10977723 0.84837954]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [47]:
Z = np.random.random((10))
print('maximum of Z:',np.max(Z))
Z[Z.argmax()] = 0
print('\n',Z)

maximum of Z: 0.8814240021304577

 [0.42308168 0.         0.7675858  0.66902572 0.42112845 0.873603
 0.64040038 0.69539472 0.76389539 0.42498837]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [24]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print('given scalar v:',v)
index = (np.abs(Z-v)).argmin()
print(Z[index])

given scalar v: 65.05806397305491
65


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [27]:
Z = np.arange(9).reshape(3,3)

for index, x in np.ndenumerate(Z):
  print(index, x)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [28]:
n = 5
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False), 7)
print(Z)


[[0. 0. 0. 0. 7.]
 [0. 0. 0. 0. 0.]
 [7. 0. 0. 0. 7.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [33]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[5 6 3]
 [8 7 1]
 [8 7 6]]
[[5 6 3]
 [8 7 1]
 [8 7 6]]


In [34]:
# column 2
print(Z)
print(Z[Z[:,1].argsort()])

[[5 6 3]
 [8 7 1]
 [8 7 6]]
[[5 6 3]
 [8 7 1]
 [8 7 6]]


In [35]:
# column 3
print(Z)
print(Z[Z[:,2].argsort()])

[[5 6 3]
 [8 7 1]
 [8 7 6]]
[[8 7 1]
 [5 6 3]
 [8 7 6]]
